<h1>a_tensor_initialization.py<h1>

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1,2,3], device='cpu') # 
print(t1.dtype)         # dtype의 경우 텐서의 자료형을 알려주는 변수입니다.
print(t1.device)        # device의 경우 텐서가 cpu위에 있는지 gpu위에 있는지 알려줍니다.
print(t1.requires_grad) # requires_grad의 경우 True 일 경우 이 텐서에 대한 기울기를 저장하게 됩니다.
print(t1.size())        # size()함수의 경우 이 텐서의 크기를 알려주는 함수입니다.
print(t1.shape)         # shape는 size()함수와 마찬가지로 텐서의 크기를 알려줍니다.

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


 - 위 코드는 torch.Tensor클래스의 기본적인 클래스 변수와 함수에 대한 설명입니다.

In [3]:
t1_cuda = t1.to(torch.device('cuda'))   # 텐서가 gpu상에서 작동하도록 to함수를 이용해서 변경해 주었습니다.
t1_cuda = t1.cuda()                     # cuda()함수를 통해서 gpu상에서 작동하도록 해주었습니다.
t1_cpu = t1.cpu()                       # cpu()함수를 통해서 cpu상에서 작동하도록 해주었습니다.

In [4]:
t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype)         # t1과 다른 점은 Tensor가 아닌 tensor를 사용해서 자료형이 int64설정 되었습니다.
print(t2.device)        # device의 경우 t1과 마찬가지로 cpu입니다.
print(t2.requires_grad) # >>> False (t1에서 설명함)
print(t2.size())        # t1과 마찬가지로 자료형만 다르고 크기는 같아 torch.Size([3])이 나옵니다.
print(t2.shape)         # > torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


 - torch.Tensor()와 torch.tensor()을 사용하여 텐서를 만들고 텐서의 형태, 크기, 자료형 등을 알아 보았다.

In [5]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim) # ndim은 텐서의 차원을 알려줍니다. 
# 텐서의 차원은 []의 개수로 정해집니다. a1텐서는 (1)이므로 차원이 0차원이어서 크기도 출력이 되지 않습니다.

torch.Size([]) 0


In [6]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim) #텐서가 [1]이므로 차원은 1이고 안에 차원안에 들어있는 요소의 개수가 1개이므로 크기가 1입니다.

torch.Size([1]) 1


In [7]:
a3 = torch.tensor([1, 2, 3, 4, 5]) 
print(a3.shape, a3.ndim) #텐서가 [1,2,3,4,5]이므로 차원은 1이고 안에 요소의 개수가 5개이므로 크기가 5입니다.

torch.Size([5]) 1


In [8]:
a4 = torch.tensor([[1],[2],[3],[4],[5]])
print(a4.shape, a4.ndim) #텐서가 [[1],[2],[3],[4],[5]]이므로 차원은 2이다.
# 차원이 2개이므로 가장 안쪽 차원은 요소가 1개있고 이 바깥쪽 차원은 5개의 요소가 있으므로 텐서의 크기는 [5, 1]이다.

torch.Size([5, 1]) 2


In [9]:
a5 = torch.tensor([                
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim) # 텐서에서 []의 쌍의 개수가 2개로 차원은 2이다.
# 첫 번째 차원 안에는 요소가 3개가 있고 두 번째 차원 안에는 요소가 2개 있으므로 텐서의 크기는 [3, 2]이다.

torch.Size([3, 2]) 2


In [10]:
a6 = torch.tensor([                
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim) #텐서에서 []의 쌍의 개수가 3개로 차원은 3이다.
# 첫 번째 차원 안에는 요소가 3개 있고 두 번째 차원 안에는 요소가 2개 있고 세 번째 차원 안에는 요소가 1개 있어서 텐서의 크기는 [3, 2, 1]이다. 

torch.Size([3, 2, 1]) 3


In [11]:
a7 = torch.tensor([                 
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) #텐서에서 []의 쌍의 개수가 4개로 차원은 4이다.
# 첫 번째 차원은 요소가 3개, 두 번째 차원은 요소가 1개, 세 번째 차원은 요소가 2개, 네 번째 차원은 요소가 1개 있어서 텐서의 크기는 [3, 1, 2, 1]이다.

torch.Size([3, 1, 2, 1]) 4


In [12]:
a8 = torch.tensor([                
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) #텐서에서 []의 쌍의 개수가 4개로 차원은 4이다.
# 첫 번째 차원은 요소가 3개, 두 번째 차원은 요소가 1개, 세 번째 차원은 요소가 2개, 네 번째 차원은 요소가 3개 있어서 텐서의 크기는 [3, 1, 2, 3]이다.

torch.Size([3, 1, 2, 3]) 4


In [13]:
a9 = torch.tensor([                 
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) #텐서에서 []의 쌍의 개수가 5개로 차원은 5이다.
# 첫 번째 차원은 요소가 3개, 두 번째 차원은 요소가 1개, 세 번째 차원은 요소가 2개, 네 번째 차원은 요소가 3개, 
# 다섯 번째 차원은 요소가 1개 있어서 텐서의 크기는 [3, 1, 2, 3, 1]이다.

torch.Size([3, 1, 2, 3, 1]) 5


In [15]:
a10 = torch.tensor([                
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim) #텐서에서 []의 쌍의 개수가 2개로 차원은 2이다.
# 첫 번째 차원은 요소가 4개, 두 번째 차원은 요소가 5개로 텐서의 크기는 [4, 5] 이다.

torch.Size([4, 5]) 2


In [ ]:
a11 = torch.tensor([                
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
]) # 이 텐서의 경우 각 차원의 내부의 크기가 같아야 하는데 같지 않아 오류를 일으킨다.

<H1>b_tensor_initialization_copy.py<H1>

In [17]:
import numpy as np

In [19]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)   #list l1을 이용해서 Tensor를 만들었다.(dtype = float32)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)   #list l2을 이용해서 tensor를 만들었다. (dtype = int64)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)   #list l3을 이용해서 tensor를 만들었다.

l1[0] = 100             #tensor를 만들 때 list의 참조 값을 복사하는 것이 아닌 내부 값을 자체를 복사하기 때문에 값을 변경해도 출력값이 변하지 않는다. 
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


 - list를 이용해서 tensor를 생성할 때는 list에 값 자체를 복사하여 tensor를 생성한다.

In [20]:
l4 = np.array([1, 2, 3])  
t4 = torch.Tensor(l4)       #numpy의 배열을 이용해서 datatype이 float32인 텐서를 만들 수 있다. 

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)       #numpy의 배열을 이용해서 datatype이 int32인 텐서를 만들 수 있다.

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)    #numpy의 배열을 이용해서 datatype이 int32인 텐서를 만들 수 있다.

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)
#t4와 t5의 경우 numpy의 배열에 첫번째 요소를 100으로 바꾸었을 때 텐서는 바뀌지 않았지만 t6의 경우 값이 바뀐 것을 통해서 
#as_tensor()의 경우 numpy의 배열은 참조값을 복사해서 값이 변경이 되었다. 

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


 - 리스트와 numpy배열을 tensor로 바꾸는 과정을 실행하였다.

<H1>c_tensor_initialization_constant_values.py<H1>

In [2]:
import torch

In [21]:
t1 = torch.ones(size=(5,))              # ones()함수는 텐서의 값들을 전부 1로 해서 만들어 준다. 이 경우 차원 1이고 크기가[5]인 텐서에 값은 모두 1이다.
t1_like = torch.ones_like(input=t1)     # ones_like()함수는 input값에 들어 있는 텐서의 차원과 크기가 같은 텐서에 값은 모두 1로 되어 있는 텐서를 만들어 준다.
print(t1)  
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [3]:
t2 = torch.zeros(size=(6,))             #zeros()함수는 텐서의 값들을 전부 0으로 해서 만들어 준다. 이 경우 차원 1이고 크기가[6]인 텐서에 값은 모두 0이다.
t2_like = torch.zeros_like(input=t2)    #ones_like()함수는 input값에 들어 있는 텐서의 차원과 크기가 같은 텐서에 값은 모두 0으로 되어 있는 텐서를 만들어 준다.
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [29]:
t3 = torch.empty(size=(4,))             #empty()함수는 아무값도 초기화 되지 않은 텐서를 만들어준다. 텐서의 각 값들은 쓰레기 값이 나온다.
t3_like = torch.empty_like(input=t3)    #empty_like()함수는 input값에 들어 있는 텐서의 차원과 크기가 같은 텐서에 값은 모두 초기화 되어 있지 않는 텐서를 만든다.
print(t3) 
print(t3_like)  

tensor([2.3694e-38, 2.0000e+00, 1.7756e+00, 4.5491e-01])
tensor([2.3694e-38, 2.0000e+00, 1.7756e+00, 4.5491e-01])


In [30]:
t4 = torch.eye(n=3)                     #eye()함수는 단위행렬과 형태가 같은 텐서를 만들어 준다.
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


 - 텐서를 만들어주는 ones, zeros, empty, eye()함수를 사용하여 각 텐서를 출력하였다.

<H1>d_tensor_initialization_random_values.py<H1>

In [31]:
import torch

In [32]:
#randint()함수는 지정된 범위 low~high에서 랜덤한 정수들로 채워진 텐서를 생성한다.
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[12, 19]])


In [33]:
#rand()함수는 0과 1 사이의 랜덤한 실수로 채워진 텐서를 생성한다. 
t2 = torch.rand(size=(1, 3)) 
print(t2)

tensor([[0.2315, 0.6328, 0.6561]])


In [34]:
#randn() 함수는 평균이 0이고 표준편차 1을 따르는 정규분포로부터의 값으로 채워진 텐서를 생성한다.
t3 = torch.randn(size=(1, 3)) 
print(t3)

tensor([[ 1.9232,  0.5376, -0.9350]])


In [38]:
#normal()함수는 평균과 표준편차를 매개변수로 받아 그것들을 따르는 정규분포로부터의 값으로 채워진 텐서를 생성한다.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[ 9.1848,  9.6201],
        [12.0301, 10.0804],
        [ 9.1879,  8.9104]])


In [39]:
#linspace()함수는 start부터 end까지 steps개의 동일한 간격으로 나누어진 값을 가진 텐서를 생성한다.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [40]:
#arange()함수는 0부터 (매개변수로 받는 값-1)까지의 정수로 구성된 1차원 텐서를 생성한다.
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


In [41]:
torch.manual_seed(1729) # torch.manual_seed로 난수 생성 시드를 고정할 수 있다.

In [42]:
#random1과 random2는 0과 1 사이의 랜덤한 실수로 채워진 2*3텐서를 생성한다.
random1 = torch.rand(2, 3)
print(random1)
random2 = torch.rand(2, 3)
print(random2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [43]:
torch.manual_seed(1729)

In [44]:
#random3는 동일한 시드로 인해 random1과 같은 텐서를 생성한다.
random3 = torch.rand(2, 3)
print(random3)
#random4는 동일한 시드로 인해 random2과 같은 텐서를 생성한다.
random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


 - 랜덤한 값으로 텐서를 생성하거나 정규분포를 통해서 텐서를 생성하였고 시드를 고정시켜서 랜덤한 값을 지정해줄 수 있도록 해주는 코드를 실행하였다.

<H1>e_tensor_type_conversion.py<H1>

In [45]:
import torch

In [46]:
#a는 2*3 크기의 1로 채워진 텐서를 생성한다.
a = torch.ones((2, 3))
print(a.dtype)          #기본적으로 ones의 데이터 타입은 float32여서 torch.float32가 출력된다.

torch.float32


In [47]:
#b는 2*3 크기의 1로 채워진 텐서를 생성한다. 데이터 타입은 int16으로 지정한다.
b = torch.ones((2, 3),dtype=torch.int16)    
print(b)                                    #데이터 타입은 torch.int16로 출력된다.

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [48]:
#c는 2*3크기의 랜덤한 값으로 채워진 텐서 생성 후 20을 곱하고 데이터 타입은 float64로 지정한다.
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)        #데이터 타입은 torch.float64로 출력된다.

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)


In [49]:
#d는 b에서 데이터 타입을 int32로 변환한 텐서이다.
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [50]:
double_d = torch.ones(10, 2, dtype=torch.double)        #double_d는 10*2크기의 1로 채워진 텐서를 생성하고 데이터 타입은 double이다.
short_e = torch.tensor([[1, 2]], dtype=torch.short)     #short_e는 2차원 리스트를 통해 구성된 텐서를 생성하고 데이터 타입은 short이다.
double_d = torch.zeros(10, 2).double()                  #double_d는 10*2크기의 0으로 채워진 텐서를 생성하고 데이터 타입은 double이다.
short_e = torch.ones(10, 2).short()                     #short_e는 10*2크기의 1로 채워진 텐서를 생성하고 데이터 타입은 short이다.
double_d = torch.zeros(10, 2).to(torch.double)          #double_d는 10*2크기의 0으로 채워진 텐서를 생성하고 데이터 타입은 double이다.
short_e = torch.ones(10, 2).to(dtype=torch.short)       #short_e는 10*2크기의 1로 채워진 텐서를 생성하고 데이터 타입은 short이다.

In [51]:
print(double_d.dtype) #double = float64
print(short_e.dtype)  #short = int16

torch.float64
torch.int16


In [52]:
double_f = torch.rand(5, dtype=torch.double)            #double_f는 5개의 랜덤한 값으로 채워진 텐서를 생성하고 데이터 타입은 double이다.
short_g = double_f.to(torch.short)                      #short_g는 double_f 텐서를 short타입으로 변환한 것이다.
print((double_f*short_g).dtype)                         #double_f와 short_g를 곱한 결과의 데이터 타입 출력한다. 이때 더 범위가 큰쪽의 데이터 타입으로 맞춰진다.

torch.float64


 - 텐서를 생성할 때 어떤 데이터 타입으로 생성되는지 알아보고 텐서의 데이터 타입을 변화시키는 코드를 실행하였다.

<H1>f_tensor_operations.py<H1>

In [53]:
import torch

In [54]:
#t1과 t2는 2*3크기의 1로 채워진 텐서를 생성한다.
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
#add()함수를 사용해서 t1과 t2의 합을 구한다
t3 = torch.add(t1, t2)
#t1과 t2의 합을 연산자 +를 사용하여 계산한다.
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [55]:
#sub()함수를 사용해서 t1과 t2의 차를 구한다
t5 = torch.sub(t1, t2)
#t1과 t2의 차를 연산자 -를 사용하여 계산한다.
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
#mul()함수를 사용해서 t1과 t2의 곱을 구한다
t7 = torch.mul(t1, t2)
#t1과 t2의 곱을 연산자 *를 사용하여 계산한다.
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
#div()함수를 사용해서 t1과 t2의 나눗셈을 구한다
t9 = torch.div(t1, t2)
#t1과 t2의 나눗셈을 연산자 /를 사용하여 계산한다.
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


 - 텐서의 덧셈, 뺄셈, 곱셈, 나눗셈을 함수와 연산자를 이용해서 계산하였다.

<H1>g_tensor_operations_mm.py<H1>

In [60]:
import torch

In [61]:
#dot()함수는 두 벡터의 내적을 계산하는 함수이다.
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) #내적의 결과와 크기를 출력한다.(내적의 크기의 경우 Size([])이다.)

tensor(7) torch.Size([])


In [62]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
#t4에서 mm()함수는 행렬 곱을 계산해주는 함수이다.
t4 = torch.mm(t2, t3)
print(t4, t4.size()) #t2와 t3의 행렬 곱의 결과는 2*2크기의 행렬이다.

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [63]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
#t7에서 bmm은 배치 행렬 곱을 계산하는 함수이다. 배치 행렬 곱의 경우 3차원 텐서 간의 행렬 곱셈을 수행한다.
t7 = torch.bmm(t5, t6)
print(t7.size()) # 첫 번째 차원이 배치 크기를 나타내고 각 배치에서 2차원 텐서 간의 곱셈이 진행되어 10*3*5크기의 텐서가 생성된다.

torch.Size([10, 3, 5])


 - 텐서의 내적, 행렬 곱, 배치 행렬 곱을 수행하였다. 

<H1>h_tensor_operations_matmul.py<H1>

In [64]:
import torch

In [65]:
#matmul()함수의 경우 뒤에 오는 텐서들의 조합에 따라 dot, mm, bmm이 실행될지 결정되고 이때 broadcasting이 진행된다.
t1 = torch.randn(3)
t2 = torch.randn(3)
#t1과 t2의 경우 벡터 * 벡터이므로 dot연산이 진행된다.
print(torch.matmul(t1, t2).size())

torch.Size([])


In [66]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
#t3와 t4의 경우 matrix * vector이므로 broadcasted dot연산이 진행된다. 
print(torch.matmul(t3, t4).size()) 

torch.Size([3])


In [70]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
#t5와 t6의 경우 batched matrix * vector이므로 broadcasted dot연산이 진행된다.
print(torch.matmul(t5, t6).size())

torch.Size([10, 3])


In [71]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
#t7와 t8의 경우 batched matrix * batched matrix이므로 bmm연산이 진행된다. 
print(torch.matmul(t7, t8).size()) 

torch.Size([10, 3, 5])


In [73]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
#t9와 t10의 경우 batched matrix * matrix이므로 t10이 shape가 ([10,4,5])로 broadcasted가 된 후 bmm연산이 진행된다. 
print(torch.matmul(t9, t10).size()) 

torch.Size([10, 3, 5])


 - matmul연산이 텐서의 shape에 따라 어떤 연산이 진행되는지 알아보았다.

<H1>i_tensor_broadcasting.py<H1>

In [72]:
import torch

In [74]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
#t1과 t2의 곱은 텐서와 스칼라의 곱이니 t2가 broadcasted되어 t1에 곱해진다.
print(t1 * t2)

tensor([2., 4., 6.])


In [75]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
#t3과 t4의 차는 텐서와 스칼라의 차이니 t4가 broadcasted되어 t3에 뺀다.
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [76]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # broadcasting 되어 각 요소에 2.0 더하기
print(t5 - 2.0)  # broadcasting 되어 각 요소에 2.0 빼기
print(t5 * 2.0)  # broadcasting 되어 각 요소에 2.0 곱하기
print(t5 / 2.0)  # broadcasting 되어 각 요소를 2.0으로 나누기

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [77]:
# normalize 함수: 입력을 255로 나누어 반환하는 함수
def normalize(x):
  return x / 255

In [78]:
t6 = torch.randn(3, 28, 28)
#normalize함수에 들어가도 broadcasting이 되어 각 요소에 255가 나누어 진다. 그래서 shape의 변화가 없다.
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [79]:
#추가 구문
t6_add = torch.randn(1, 2, 3)
print(t6_add)
#normalize가 각 요소가 255로 나누어지는 지 확인
print(normalize(t6_add))

tensor([[[-0.3289,  0.4161, -0.0105],
         [-0.3281,  0.5704,  0.3084]]])
tensor([[[-1.2897e-03,  1.6317e-03, -4.1068e-05],
         [-1.2867e-03,  2.2368e-03,  1.2093e-03]]])


In [80]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])          # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])        # torch.Size([2, 1])
t10 = torch.tensor([7])              # torch.Size([1])
print(t7 + t8)                       # t8이 [1,2]이 [2,2]로 broadcasting되어 연산 진행된다.
print(t7 + t9)                       # t9이 [2,1]이 [2,2]로 broadcasting되어 연산 진행된다.
print(t8 + t9)                       # t8이 [1,2]이 [2,2]로 broadcasting되어, t9이 [2,1]이 [2,2]로 broadcasting되어 덧셈이 진행된다.
print(t7 + t10)                      # t10이 [1]이 [2,2]로 broadcasting되어 덧셈이 진행된다.

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [81]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
#torch.rand(3,2)이 [4,3,2]로 broadcasting되어 곱셈 연산이 진행되어 t12의 shape가 [4,3,2]이다.
print(t12.shape)  

torch.Size([4, 3, 2])


In [82]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1) 
#torch.rand(3,1)이 [4,3,2]로 broadcasting되어 곱셈 연산이 진행되어 t14의 shape가 [4,3,2]이다.
print(t14.shape)  

torch.Size([4, 3, 2])


In [83]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2) 
#torch.rand(1,2)이 [4,3,2]로 broadcasting되어 곱셈 연산이 진행되어 t16의 shape가 [4,3,2]이다.
print(t16.shape)

torch.Size([4, 3, 2])


In [85]:
t17 = torch.ones(5, 3, 4, 1)            # 4차원 텐서
t18 = torch.rand(3, 1, 1)               # 3차원 텐서
#t18이 3차원 텐서인데 4차원 텐서로 broadcasting되어 덧셈이 진행된다.
print((t17 + t18).size()) 

torch.Size([5, 3, 4, 1])


In [86]:
t19 = torch.empty(5, 1, 4, 1)           # 4차원 텐서
t20 = torch.empty(3, 1, 1)              # 3차원 텐서
#t20이 3차원 텐서인데 4차원 텐서로 broadcasting되어 덧셈이 진행된다.
print((t19 + t20).size())  

torch.Size([5, 3, 4, 1])


In [87]:
t21 = torch.empty(1)                     # 스칼라 텐서
t22 = torch.empty(3, 1, 7)               # 3차원 텐서
#t20이 스칼라인데 3차원 텐서로 broadcasting되어 덧셈이 진행된다.
print((t21 + t22).size())  

torch.Size([3, 1, 7])


In [88]:
t23 = torch.ones(3, 3, 3)                # 3차원 텐서
t24 = torch.ones(3, 1, 3)                # 3차원 텐서
#이 경우 t23과 t24가 차원은 3차원으로 같지만 크기가 같지 않아서 크기를 같게 broadcasting해준 뒤 덧셈이 진행된다.
print((t23 + t24).size()) 

torch.Size([3, 3, 3])


In [89]:
# t27: 1차원 텐서에 모든 요소에 5 곱한다
t27 = torch.ones(4) * 5
print(t27)  # tensor([ 5., 5., 5., 5.])

tensor([5., 5., 5., 5.])


In [90]:
# t28은 t27의 각 요소를 제곱해 주었다
t28 = torch.pow(t27, 2)
print(t28)  # tensor([ 25., 25., 25., 25.])

tensor([25., 25., 25., 25.])


In [93]:
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)    # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)     # a의 각 요소를 exp의 각 요소로 제곱하였다.
print(t29)

tensor([  1.,   4.,  27., 256.])


 - broadcasting이 어떻게 진행되는지 알아보는 코드를 작성하였다.

<H1>j_tensor_indexing_slicing.py<H1>

In [94]:
import torch

In [95]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

In [96]:
print(x[1])         #x의 첫 번째 차원에 인덱스가 1인 요소들을 출력한다.
print(x[:, 1])      #x의 첫 번째 차원은 전부 가져오고, 두 번째 차원에서 인덱스가 1에 해당하는 요소들만 출력한다.
print(x[1, 2])      #x의 첫 번째 차원에 인덱스가 1이고 두 번째 차원에서 인덱스가 2에 해당하는 요소를 출력한다.
print(x[:, -1])     #x의 첫 번째 차원은 전부 가져오고, 두 번째 차원에서 마지막 인덱스에 해당하는 요소들만 출력한다.

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [97]:
print(x[1:]) # 1행부터 끝까지의 모든 요소를 출력한다.

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [98]:
print(x[1:, 3:]) # 1행부터 끝까지의 3열부터 끝까지의 요소를 출력한다.

tensor([[ 8,  9],
        [13, 14]])


In [99]:
y = torch.zeros((6, 6))
# y의 1열에서 3열까지의 2번째 열에 1 할당한다.
y[1:4, 2] = 1
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [100]:
print(y[1:4, 1:4]) # y의 1행부터 3행까지, 1열부터 3열까지 슬라이싱하여 출력한다.

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [101]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

In [102]:
print(z[:2]) #z의 0행부터 1행까지 슬라이싱하여 출력한다.

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])


In [103]:
print(z[1:, 1:3]) #z의 1행부터 끝까지, 1열부터 2열까지 슬라이싱하여 출력한다.

tensor([[3, 4],
        [6, 7]])


In [104]:
print(z[:, 1:]) #z의 모든 행에서 1열부터 끝까지 슬라이싱하여 출력한다.

tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [105]:
z[1:, 1:3] = 0 #z의 1행부터 끝까지의 1열과 2열에 0 할당한다.
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


 - 텐서의 slicing 기술을 이용해서 수를 할당하거나 해당하는 행과 열을 가져오는 코드를 수행하였다.

<H1>k_tensor_reshaping.py<H1>

In [106]:
import torch

In [108]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])   # Shape가 (2, 3)이다. 
t2 = t1.view(3, 2)                          # Shape를 (3,2)로 변경한다.
t3 = t1.reshape(1, 6)                       # Shape를 (1,6)로 변경한다.
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [109]:
t6 = torch.tensor([[[1], [2], [3]]]) #Shape가 (1, 3, 1)이다
print(t6.shape)

torch.Size([1, 3, 1])


In [111]:
t7 = t6.squeeze()       #매개변수가 비어 있으면 크기가 1인 모든 차원을 삭제한다.
t8 = t6.squeeze(0)      #첫번째 차원을 삭제한다.
print(t7)               #Shape가 (3)이다.
print(t7.shape)
print(t8)               #Shape가 (3,1)이다.
print(t8.shape)

tensor([1, 2, 3])
torch.Size([3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [112]:
t9 = torch.tensor([1, 2, 3]) #shape가 (3)이다.
t10 = t9.unsqueeze(1)        #위치가 1인곳에 새로운 차원을 추가한다.
print(t10)                   #shape가 (3,1)이다.

tensor([[1],
        [2],
        [3]])


In [113]:
t11 = torch.tensor(     #shape가 (2,3)이다.
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  #위치가 1인곳에 새로운 차원을 추가한다. 이러면 t12의 shape는 (2, 1, 3)이다.
print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [114]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten() #flatten()함수는 매개변수가 없으면 1차원 텐서로 만들어 준다.
print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [117]:
#추가 코드
t13_add = torch.tensor([[[[2,3],[4,2]],[[4,5],[6,7]]]])
t14_add = t13_add.flatten() #2차원 뿐만 아니라 3차원 그 이상도 1차원 텐서로 만들어 준다
print(t14_add)

tensor([2, 3, 4, 2, 4, 5, 6, 7])


In [118]:
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15) #t15를 1차원 텐서로 만들어 준다.

t17 = torch.flatten(t15, start_dim=1) #t15에서 두 번째 차원부터 1차원으로 변환한다.
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [119]:
#추가 코드
t17_add = torch.flatten(t15, start_dim=0, end_dim=1) #t15에서 첫 번째 차원부터 두 번째 차원까지만 1차원으로 변환한다.
print(t17_add)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [120]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size()) #permute()함수는 t18의 차원을 (2, 0, 1)순서로 변경한다.

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [121]:
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t20 = torch.permute(t19, dims=(0, 1)) # t19의 차원을 변경 (0, 1)으로 permute, 형태는 (2, 3) 그대로 유지된다.
t21 = torch.permute(t19, dims=(1, 0)) # t19의 차원을 변경 (1, 0)으로 permute, 형태가 (3, 2)로 변환된다.
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [122]:
t22 = torch.transpose(t19, 0, 1) #transpose()함수는 차원 2개를 전치하는 함수이다.
print(t22)  

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [123]:
t23 = torch.t(t19)  ## 2D 텐서의 경우 torch.transpose와 동일하게 작동한다.
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


  - 텐서의 shape를 변경할 수 있는 함수들을 사용하였다.

<H1>l_tensor_concat.py<H1>

In [124]:
import torch

In [125]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

In [126]:
t4 = torch.cat([t1, t2, t3], dim=1) #cat()함수의 경우 특정 차원을 기준으로 연결을 해주는 함수이다.
#t4는 1차원을 기준으로 t1, t2, t3를 합친다. 그래서 0차원과 2차원은 크기가 고정되고 1차원이 1+3+2로 크기가 6이 된다.
print(t4.shape)

torch.Size([2, 6, 3])


In [127]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])
t7 = torch.cat((t5, t6), dim=0) #첫 번째 차원을 기준으로 하여 t5, t6를 연결한다.
print(t7.shape)
print(t7) 

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [128]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3) 
t10 = torch.cat((t8, t9), dim=0) # 0차원을 기준으로 하여 t8, t9를 연결한다.
print(t10.size())
print(t10)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [129]:
t11 = torch.cat((t8, t9), dim=1) # 1차원을 기준으로 하여 t8, t9를 연결한다.
print(t11.size())
print(t11)

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [130]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)
t15 = torch.cat((t12, t13, t14), dim=0) # 0차원을 기준으로 하여 t12, t13, t14를 연결한다.
print(t15.size())
print(t15)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [131]:
t16 = torch.cat((t12, t13, t14), dim=1) # 1차원을 기준으로 하여 t12, t13, t14를 연결한다.
print(t16.size())
print(t16)

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [132]:
t17 = torch.arange(0, 6).reshape(1, 2, 3) 
t18 = torch.arange(6, 12).reshape(1, 2, 3)
t19 = torch.cat((t17, t18), dim=0) # 0차원을 기준으로 하여 t17, t18을 연결한다.
print(t19.size())
print(t19)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [133]:
t20 = torch.cat((t17, t18), dim=1) # 1차원을 기준으로 하여 t17, t18을 연결한다.
print(t20.size()) 
print(t20) 

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


In [134]:
t21 = torch.cat((t17, t18), dim=2) # 2차원을 기준으로 하여 t17, t18을 연결한다.
print(t21.size())  
print(t21) 

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


 - cat()함수를 이용해서 텐서를 병합(연결)하는 코드를 수행하였다.

<H1>m_tensor_stacking.py<H1>

In [135]:
import torch

In [136]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
t3 = torch.stack([t1, t2], dim=0)  #stack()함수의 경우 새로운 차원을 확장해서 합치게 된다. 
#t1과 t2의 shaep이 (2,3)인데 새로운 차원을 확장하여 (1,2,3)을 합치게 된다. 그래서 t3의 shape는 (2,2,3)이 된다.
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) #이 과정이 unsqueeze해서 차원을 늘리고 cat으로 합치는 과정이 stack함수와 같은 역할을 한다.
print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [137]:
t5 = torch.stack([t1, t2], dim=1) #이 경우 t1과 t2의 shape이 (2, 1, 3)으로 만들어지고 dim=1을 기준으로 합쳐진다.
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [138]:
t7 = torch.stack([t1, t2], dim=2) #이 경우 t1과 t2의 shape이 (2, 3, 1)으로 만들어지고 dim=2을 기준으로 합쳐진다.
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [139]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])
print(t9.size(), t10.size()) # >>> torch.Size([3]) torch.Size([3])

torch.Size([3]) torch.Size([3])


In [140]:
t11 = torch.stack((t9, t10), dim=0) #t9, t10의 shape가 (1,3)으로 확장되고 dim=0 기준으로 합쳐진다.
print(t11.size())  # 
print(t11)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [141]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0) #stack과 같은 과정으로 unsqueeze로 확장하고 cat으로 병합한다.
print(t11.equal(t12)) #이러면 t11과 똑같은 텐서가 만들어진다.

True


In [142]:
t13 = torch.stack((t9, t10), dim=1)  #t9, t10의 shape가 (3, 1)으로 확장되고 dim=1 기준으로 합쳐진다.
print(t13.size())  
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [143]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1) #stack과 같은 과정으로 unsqueeze로 확장하고 cat으로 병합한다.
print(t13.equal(t14)) #이러면 t13과 똑같은 텐서가 만들어진다.

True


 - stacking이 어떻게 진행되는지 보고 unsqueeze와 cat을 이용해서 stack과 같은 연산을 하도록 만드는 코드를 수행하였다.

<H1>n_tensor_vstack_hstack.py<H1>

In [144]:
import torch

In [145]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) #vstack()함수는 텐서들을 수직방향으로 결합하는 함수이다. 
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [146]:
t4 = torch.tensor([[1], [2], [3]])  # 3x1 텐서
t5 = torch.tensor([[4], [5], [6]])  # 3x1 텐서
t6 = torch.vstack((t4, t5)) # 텐서 t4와 t5를 수직 방향으로 결합하여 6*1텐서를 생성한다.
print(t6)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [147]:
t7 = torch.tensor([  # 2x2x3 텐서
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

torch.Size([2, 2, 3])


In [148]:
t8 = torch.tensor([  # 2x2x3 텐서
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape) 

torch.Size([2, 2, 3])


In [149]:
t9 = torch.vstack([t7, t8])  # t7과 t8을 수직 방향으로 결합하여 4x2x3 텐서 생성한다.
print(t9.shape)
print(t9)

torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [150]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) #hstack()함수는 수평 방향으로 텐서를 결합한다. 텐서 t10과 t11을 수평 방향으로 결합하여 1차원 텐서를 만든다.
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [152]:
t13 = torch.tensor([[1], [2], [3]])  # 3x1 텐서
t14 = torch.tensor([[4], [5], [6]])  # 3x1 텐서
t15 = torch.hstack((t13, t14))       # 수평 결합(hstack)으로 3x2 텐서 생성한다.
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [153]:
t16 = torch.tensor([  
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
t17 = torch.tensor([  
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [154]:
t18 = torch.hstack([t16, t17]) #t16과 t17을 수평 방향으로 결합하여 2x4x3 텐서 생성한다.
print(t18.shape)
print(t18)

torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


 - hstack과 vstack을 이용해서 수직, 수평으로 결합하는 코드를 수행하였다. 